name: build-directory-test
on: push
jobs:
  build-jekyll-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
      - run: bundle install
      - run: bundle exec jekyll build
