name: build-site
on: 
  pull_request:
    branches: 
      - main
        
jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
      - name: Run bundle install
        run: bundle install
      - name: Build site
        run: bundle exec jekyll build
