name: link-checker
on: push
jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Install node
        uses: actions/setup-node@v2
      - name: Install Markdown link checker
        run: npm install markdown-link-checker
